services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  app:
    build: .
    ports:
      - 8080:3000
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DO_SEED=${DO_SEED}
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - PROD_HOST_URL=${PROD_HOST_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_ENDPOINT=${STRIPE_WEBHOOK_ENDPOINT}
      - HONEYPOT_ENCRYPTION_SEED=${HONEYPOT_ENCRYPTION_SEED}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
